version: "3.3"
services:
  api:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/github.com/ogady/find_the_right_answer/api
    environment:
      - ENV=dev

  dynamodblocal:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/ -optimizeDbBeforeStartup
    volumes:
      - ./dynamodblocalData/data:/home/dynamodblocal/data
    ports:
      - 8000:8002

  dynamodbadmin:
    image: instructure/dynamo-local-admin
    ports:
      - 8001:8000
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000/
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
    depends_on:
      - dynamodblocal

volumes:
  dynamodblocalData:
    driver: local
